RECEIVE_DECRYPT_FILE = 0
RECEIVE_DECRYPT_PW = 1

RECEIVE_ENCRYPT_FILE = 0
RECEIVE_ENCRYPT_PW = 1

RECEIVE_MERGE_FILE = 0

RECEIVE_ROTATE_FILE = 0
ROTATE_FILE = 1

RECEIVE_SPLIT_FILE = 0
SPLIT_FILE = 1

RECEIVE_WATERMARK_SOURCE_FILE = 0
RECEIVE_WATERMARK_FILE = 1
WATERMARK_FILE = 2
