WAIT_TASK = 0
WAIT_DECRYPT_PW = 1
WAIT_ENCRYPT_PW = 2
WAIT_ROTATE_DEGREE = 3
WAIT_SCALE_BY_X = 4
WAIT_SCALE_BY_Y = 5
WAIT_SCALE_TO_X = 6
WAIT_SCALE_TO_Y = 7
WAIT_SPLIT_RANGE = 8

WAIT_MERGE_FILE = 0

WAIT_WATERMARK_SOURCE_FILE = 0
WAIT_WATERMARK_FILE = 1
