RECEIVE_PDF_FILE = 0
RECEIVE_DECRYPT_PW = 1
RECEIVE_ENCRYPT_PW = 2
RECEIVE_ROTATE_DEGREE = 3
RECEIVE_SCALE_BY_X = 4
RECEIVE_SCALE_BY_Y = 5
RECEIVE_SCALE_TO_X = 6
RECEIVE_SCALE_TO_Y = 7
RECEIVE_SPLIT_RANGE = 8

RECEIVE_MERGE_FILE = 0

RECEIVE_WATERMARK_SOURCE_FILE = 0
RECEIVE_WATERMARK_FILE = 1
