name: Pull request target actions

on:
  pull_request_target:

jobs:
  pull-request:
    uses: zeshuaro/github-actions-workflows/.github/workflows/pull-request-target.yml@92fcccd49973601e8e1855ea945a8a4ab53d80a5 # main
