name: Pull request target actions

on:
  pull_request_target:

jobs:
  pull-request:
    uses: zeshuaro/github-actions-workflows/.github/workflows/pull-request-target.yml@803ca289e2a15f358d882e07ae6e30547ac8f5dd # main
