name: Scheduled actions

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  scheduled:
    uses: zeshuaro/github-actions-workflows/.github/workflows/scheduled.yml@7a3db4b1754b640ee41681c4896ed07b8a8aaace # main
    secrets:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
