name: Scheduled actions

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  scheduled:
    uses: zeshuaro/github-actions-workflows/.github/workflows/scheduled.yml@4599947489f914a550da8207f1b06e9408b900fa # main
    secrets:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
